-- Gerado por scripts/gerar-seed-questoes.mjs — não editar à mão.
delete from public.questoes where lesson_slug in ('ds/logica-de-programacao/1-bimestre/semana-01-introducao', 'enem/fisica/cinematica', 'enem/geometria/geometria-plana', 'escolar/historia/1-bimestre/semana-01-chegada-portugueses', 'escolar/matematica/1-bimestre/semana-01-funcoes');

insert into public.questoes (lesson_slug, enunciado, alternativas, correct_index, explicacao, fonte) values
($seed$ds/logica-de-programacao/1-bimestre/semana-01-introducao$seed$, $seed$O que é um algoritmo?$seed$, $seed$["Um tipo de linguagem de programação, como Python","Uma sequência lógica e finita de passos para resolver um problema","Um erro de programação","Um tipo de variável","Um programa já compilado"]$seed$::jsonb, 1, $seed$Algoritmo é a ideia por trás do código — uma sequência de passos lógicos e finitos para resolver um problema. Uma receita de bolo, por exemplo, é um algoritmo.$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$ds/logica-de-programacao/1-bimestre/semana-01-introducao$seed$, $seed$Qual é a principal função de uma variável em um programa?$seed$, $seed$["Deixar o código mais bonito","Armazenar e guardar um valor que pode mudar durante a execução","Substituir os comentários do código","Executar o programa mais rápido","Corrigir erros automaticamente"]$seed$::jsonb, 1, $seed$Variável é um espaço nomeado na memória do computador usado para guardar um valor — e esse valor pode ser alterado ao longo da execução do programa, daí o nome "variável".$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$ds/logica-de-programacao/1-bimestre/semana-01-introducao$seed$, $seed$Em um algoritmo que calcula a média de duas notas, qual seria a primeira etapa lógica?$seed$, $seed$["Mostrar o resultado na tela","Somar as duas notas","Ler (receber) as duas notas de entrada","Dividir por dois","Declarar que o programa terminou"]$seed$::jsonb, 2, $seed$Todo algoritmo segue, de forma geral, a ordem: entrada de dados → processamento → saída de resultado. Antes de somar ou dividir qualquer coisa, é preciso primeiro receber os valores de entrada.$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$ds/logica-de-programacao/1-bimestre/semana-01-introducao$seed$, $seed$O que caracteriza um 'valor constante', em oposição a uma variável?$seed$, $seed$["Um valor que nunca é usado no programa","Um valor que muda a cada execução do programa","Um valor fixo que não muda durante a execução do programa","Um valor que só existe em linguagens de programação antigas","Um valor que é sempre um número"]$seed$::jsonb, 2, $seed$Constante é o oposto de variável: um valor fixo, definido uma vez, que não muda ao longo da execução do programa (por exemplo, o valor de π em um cálculo).$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$ds/logica-de-programacao/1-bimestre/semana-01-introducao$seed$, $seed$Qual das estruturas abaixo representa a ordem lógica correta e mais básica de um algoritmo?$seed$, $seed$["Saída → Processamento → Entrada","Processamento → Entrada → Saída","Entrada → Processamento → Saída","Saída → Entrada → Processamento","Não existe uma ordem lógica fixa"]$seed$::jsonb, 2, $seed$A estrutura mais básica de qualquer algoritmo é: primeiro entram os dados (Entrada), depois eles são transformados (Processamento) e, por fim, o resultado é apresentado (Saída).$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$enem/fisica/cinematica$seed$, $seed$Um ônibus percorre 90 km em 1,5 hora, sem paradas. Qual é a velocidade média desse ônibus nesse trecho?$seed$, $seed$["45 km/h","60 km/h","90 km/h","135 km/h","30 km/h"]$seed$::jsonb, 1, $seed$Velocidade média = distância total ÷ tempo total = 90 ÷ 1,5 = 60 km/h.$seed$, $seed$Questão fictícia, estilo ENEM$seed$),
($seed$enem/fisica/cinematica$seed$, $seed$Um ciclista percorre a primeira metade de um percurso de 40 km a 20 km/h e a segunda metade a 40 km/h. Qual é a velocidade média aproximada do percurso completo?$seed$, $seed$["30 km/h (média aritmética simples)","26,7 km/h","20 km/h","40 km/h","35 km/h"]$seed$::jsonb, 1, $seed$Cada metade tem 20 km. Tempo na 1ª metade = 20 ÷ 20 = 1 h. Tempo na 2ª metade = 20 ÷ 40 = 0,5 h. Tempo total = 1,5 h. Velocidade média = 40 ÷ 1,5 ≈ 26,7 km/h. A opção "30 km/h" é a pegadinha clássica de somar as velocidades e dividir por dois — isso só vale quando os tempos são iguais, não quando as distâncias são iguais.$seed$, $seed$Questão fictícia, estilo ENEM$seed$),
($seed$enem/fisica/cinematica$seed$, $seed$Um carro parte do repouso e atinge 20 m/s em 4 segundos, com aceleração constante. Qual é a aceleração desse carro?$seed$, $seed$["80 m/s²","5 m/s²","4 m/s²","16 m/s²","0,2 m/s²"]$seed$::jsonb, 1, $seed$Aceleração = variação de velocidade ÷ variação de tempo = (20 − 0) ÷ 4 = 5 m/s².$seed$, $seed$Questão fictícia, estilo ENEM$seed$),
($seed$enem/fisica/cinematica$seed$, $seed$Dois carros partem do mesmo ponto na mesma direção. O carro A viaja a 80 km/h constantes. O carro B parte 1 hora depois, a 100 km/h constantes. Quanto tempo depois da partida de B os dois carros estarão juntos novamente?$seed$, $seed$["1 hora","2 horas","3 horas","4 horas","5 horas"]$seed$::jsonb, 3, $seed$Quando B parte, A já percorreu 80 km. A partir daí, a diferença de velocidade é 100 − 80 = 20 km/h, então B "fecha" a distância de 80 km em 80 ÷ 20 = 4 horas.$seed$, $seed$Questão fictícia, estilo ENEM$seed$),
($seed$enem/fisica/cinematica$seed$, $seed$Um trem se desloca a 108 km/h. Convertendo para o Sistema Internacional, qual é essa velocidade em metros por segundo?$seed$, $seed$["10,8 m/s","18 m/s","30 m/s","108 m/s","3,6 m/s"]$seed$::jsonb, 2, $seed$Para converter km/h em m/s, divide-se por 3,6: 108 ÷ 3,6 = 30 m/s.$seed$, $seed$Questão fictícia, estilo ENEM$seed$),
($seed$enem/geometria/geometria-plana$seed$, $seed$Uma família quer trocar o piso de uma sala retangular que mede 4 metros de largura por 5 metros de comprimento. Cada caixa de piso cobre 2 m² e não pode ser fracionada. Quantas caixas, no mínimo, devem ser compradas?$seed$, $seed$["8 caixas","9 caixas","10 caixas","11 caixas","12 caixas"]$seed$::jsonb, 2, $seed$Área da sala = 4 × 5 = 20 m². Número de caixas = 20 ÷ 2 = 10 caixas exatas. Como a divisão é exata, não é preciso arredondar para cima — a pegadinha aqui é o aluno arredondar sem necessidade.$seed$, $seed$Questão fictícia, estilo ENEM$seed$),
($seed$enem/geometria/geometria-plana$seed$, $seed$Um terreno triangular tem base de 12 metros e altura de 8 metros em relação a essa base. Qual é a área desse terreno?$seed$, $seed$["20 m²","48 m²","96 m²","40 m²","60 m²"]$seed$::jsonb, 1, $seed$Área do triângulo = (base × altura) ÷ 2 = (12 × 8) ÷ 2 = 96 ÷ 2 = 48 m². O erro mais comum é esquecer de dividir por 2 e marcar 96 m².$seed$, $seed$Questão fictícia, estilo ENEM$seed$),
($seed$enem/geometria/geometria-plana$seed$, $seed$Uma praça circular tem raio de 7 metros. Usando π ≈ 22/7, qual é o perímetro (comprimento da circunferência) dessa praça?$seed$, $seed$["22 m","44 m","88 m","154 m","14 m"]$seed$::jsonb, 1, $seed$Perímetro da circunferência = 2 × π × r = 2 × (22/7) × 7 = 44 m. O valor 154 m² é a área (π × r²), não o perímetro — confundir as duas fórmulas é o erro mais comum da questão.$seed$, $seed$Questão fictícia, estilo ENEM$seed$),
($seed$enem/geometria/geometria-plana$seed$, $seed$Um pátio retangular tem 60 m² de área. Se a largura desse pátio é 6 metros, qual é o perímetro do pátio?$seed$, $seed$["16 m","20 m","26 m","32 m","36 m"]$seed$::jsonb, 3, $seed$Como área = largura × comprimento, o comprimento é 60 ÷ 6 = 10 m. Perímetro = 2 × (largura + comprimento) = 2 × (6 + 10) = 2 × 16 = 32 m. Quem esquece de multiplicar por 2 no final marca 16 m.$seed$, $seed$Questão fictícia, estilo ENEM$seed$),
($seed$enem/geometria/geometria-plana$seed$, $seed$Uma vidraçaria vai cobrir uma janela trapezoidal cujas bases medem 3 m e 5 m, com altura de 2 m entre elas. Qual é a área de vidro necessária?$seed$, $seed$["8 m²","10 m²","16 m²","4 m²","13 m²"]$seed$::jsonb, 1, $seed$Área do trapézio = [(base maior + base menor) × altura] ÷ 2 = [(5 + 3) × 2] ÷ 2 = 16 ÷ 2 = 10 m². O erro clássico é esquecer a divisão final por 2.$seed$, $seed$Questão fictícia, estilo ENEM$seed$),
($seed$escolar/historia/1-bimestre/semana-01-chegada-portugueses$seed$, $seed$Em que ano a esquadra de Pedro Álvares Cabral chegou ao território que hoje é o Brasil?$seed$, $seed$["1494","1500","1530","1549","1808"]$seed$::jsonb, 1, $seed$A esquadra de Cabral chegou em 22 de abril de 1500, na região da atual Bahia.$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$escolar/historia/1-bimestre/semana-01-chegada-portugueses$seed$, $seed$O Tratado de Tordesilhas (1494), assinado antes da chegada de Cabral, tinha como objetivo principal:$seed$, $seed$["Proibir a escravidão indígena","Dividir as terras recém-descobertas entre Portugal e Espanha","Criar as capitanias hereditárias","Estabelecer o comércio de especiarias com a Ásia","Fundar a primeira vila portuguesa na América"]$seed$::jsonb, 1, $seed$O Tratado de Tordesilhas dividiu as terras "descobertas e por descobrir" fora da Europa entre Portugal e Espanha, por meio de uma linha imaginária.$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$escolar/historia/1-bimestre/semana-01-chegada-portugueses$seed$, $seed$Qual foi o primeiro produto extrativista de destaque explorado pelos portugueses no Brasil?$seed$, $seed$["Ouro","Açúcar","Pau-brasil","Café","Algodão"]$seed$::jsonb, 2, $seed$Antes do ciclo do açúcar, o pau-brasil foi o primeiro produto explorado, usado para extração de corante vermelho para tecidos na Europa.$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$escolar/historia/1-bimestre/semana-01-chegada-portugueses$seed$, $seed$O sistema de capitanias hereditárias, criado na década de 1530, tinha como principal objetivo:$seed$, $seed$["Abolir a escravidão","Efetivar a ocupação e defesa do território contra outras nações europeias","Criar universidades na colônia","Estabelecer eleições diretas nas vilas","Encerrar o comércio com a Espanha"]$seed$::jsonb, 1, $seed$Portugal temia a invasão de franceses e outras potências europeias no litoral brasileiro, e as capitanias hereditárias foram uma forma de ocupar e defender o território a baixo custo para a Coroa.$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$escolar/historia/1-bimestre/semana-01-chegada-portugueses$seed$, $seed$Qual das alternativas descreve corretamente o sistema de capitanias hereditárias?$seed$, $seed$["Divisão do território em faixas de terra doadas a nobres, que deveriam administrá-las e defendê-las","Eleição de governadores pelos próprios colonos","Divisão de terras exclusivamente para produção de ouro","Sistema aplicado apenas depois da vinda da família real, em 1808","Substituição completa do trabalho escravo por trabalho assalariado"]$seed$::jsonb, 0, $seed$As capitanias eram grandes faixas de terra doadas a nobres portugueses (donatários), que tinham a responsabilidade de povoar, administrar e defender a área em nome da Coroa.$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$escolar/matematica/1-bimestre/semana-01-funcoes$seed$, $seed$Em uma função, cada elemento do domínio pode estar associado a quantos elementos do contradomínio?$seed$, $seed$["A no máximo dois elementos","A exatamente um único elemento","A quantos elementos forem necessários","A nenhum elemento","Depende do tipo de função"]$seed$::jsonb, 1, $seed$Essa é a definição central de função: cada entrada (domínio) tem exatamente uma saída (contradomínio) associada a ela. Se um elemento do domínio tivesse duas saídas possíveis, não seria uma função.$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$escolar/matematica/1-bimestre/semana-01-funcoes$seed$, $seed$Considere f(x) = 2x + 3. Qual é o valor de f(4)?$seed$, $seed$["7","8","9","11","14"]$seed$::jsonb, 3, $seed$f(4) = 2 × 4 + 3 = 8 + 3 = 11.$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$escolar/matematica/1-bimestre/semana-01-funcoes$seed$, $seed$Qual das opções abaixo representa o domínio de uma função?$seed$, $seed$["O conjunto de valores de saída","O conjunto de valores de entrada","O gráfico da função","A imagem da função","O eixo y do gráfico"]$seed$::jsonb, 1, $seed$Domínio é o conjunto de todos os valores de entrada (x) que a função aceita.$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$escolar/matematica/1-bimestre/semana-01-funcoes$seed$, $seed$Um gráfico representa uma função se, ao traçarmos uma linha vertical em qualquer ponto do eixo x, essa linha cruzar o gráfico:$seed$, $seed$["Em pelo menos dois pontos","Em exatamente um ponto (ou nenhum, fora do domínio)","Em infinitos pontos","Sempre na origem","Nunca deve cruzar o gráfico"]$seed$::jsonb, 1, $seed$Esse é o "teste da reta vertical": se a vertical cruza o gráfico mais de uma vez em algum ponto, significa que aquele valor de x tem duas saídas — e isso não é uma função.$seed$, $seed$Questão fictícia de fixação$seed$),
($seed$escolar/matematica/1-bimestre/semana-01-funcoes$seed$, $seed$Se f(x) = x² , qual é o valor de f(-3)?$seed$, $seed$["-9","-6","6","9","3"]$seed$::jsonb, 3, $seed$f(-3) = (-3)² = (-3) × (-3) = 9. Atenção ao sinal: número negativo ao quadrado vira positivo.$seed$, $seed$Questão fictícia de fixação$seed$);

select lesson_slug, count(*) from public.questoes group by lesson_slug order by lesson_slug;
